def find_motif_locations(s: str, t: str) -> str:
    locations = []
    len_t = len(t)

    for i in range(len(s) - len_t + 1):
        if s[i: i + len_t] == t:
            locations.append(str(i + 1))

    return " ".join(locations)

s = "CTTACTATGCTATTCTTACTAGCCTGTACTTACTAGAGACTTACTACCTTACTAGATCTTACTACTTACTAATTACCAACTTACTAAGCTCGCTACTTACTACTCCAGTCCTCCTTACTAGCGCTTACTAGTACCTTACTAGCCTTACTAAAAGCTTACTACCTTGCCTTACTAGCTTACTAAAATCTTACTACCTTACTACTTACTAAACTTACTACGACTTACTATGGGCAGGCTTACTATTCTTACTAGATTACCCTCTTACTACACTCGACCTTACTAAGTAGAATCCTTACTATCTTACTAGGCAATGTCTTACTAGATTGCTTACTACTTACTAACTTACTATTATGCTTACTAGCACTTACTAGACAGCTTACTACTAAATCTTACTACTTACTAGAACCTTACTAACTTACTATCTTACTATCCTTACTAATCGCCTTACTAGCTTCCTTACTAACTTACTATCGAAAAGAGCTTACTACTTACTAGATCTTACTACTTACTACTTACTACACCTTACTACCCTTACTAGGCTTACTAGCTTACTACTTACTATCTTACTATTCTACTTATGTCTTACTACTTACTAGGCTTACTAACCCTTACTAACCCTTACTATGTGGTGACGGACTGCTTACTACTTACTATGTATTGTTACTTACTACCTTACTACGCCTTACTAGCTTACTACTTCTTACTACTTACTAGCACTTACTAGAGTCACTTACTAACAACCTTACTACTTACTAACTTACTACCTTACTATCTTACTAACTTACTATACTCTACTTACTACGCTTACTATGCTTAGGCTTACTATTGCTTACTACACTCTTACTATGCCAGCTTACTACCATCTTACTAGGACCTTACTACGAGCTTACTACTTACTA"
t = "CTTACTACT"

result = find_motif_locations(s, t)
print(result)